name: Check for firmware and gerrit updates

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Checkout databases
      uses: actions/checkout@v3
      with:
        ref: 'refs/heads/db'
        path: 'db'

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends \
        libatk1.0-0 \
        libatk-bridge2.0-0 \
        libatspi2.0-0 \
        libgtk-3-0 \
        libgtk-4-1 \
        libdrm2 \
        libgbm1 \
        libxkbcommon0 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libxshmfence1 \
        libnss3 \
        libasound2t64 \
        libpango-1.0-0 \
        libcups2 \
        libxss1 \
        libxtst6 \
        libvpx-dev \
        libevent-2.1-7 \
        libopus0 \
        libwoff1 \
        libsecret-1-0 \
        libflite1 \
        libavif16 \
        libharfbuzz-icu0 \
        libgstreamer1.0-0 \
        libgstreamer-gl1.0-0 \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-libav \
        libhyphen0 \
        libgraphene-1.0-0 \
        libmanette-0.2-0 \
        libgles2

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
       distribution: 'temurin'
       java-version: '21'
       cache: 'maven'

    - name: Build bot
      run: |
       mvn package

    - name: Run bot
      env:
       BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
       java -jar target/fairphonebot*.jar $BOT_TOKEN @fairphone_updates oneshot

    - name: Update databases
      run: |
       git -C db config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
       git -C db config --local user.name "github-actions[bot]"
       git -C db pull origin db --ff-only
       git -C db add "*"
       git -C db commit -m "fairphonebot: $(date)" || true

    - name: Push database changes to repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'db'
        directory: 'db'
